package com.example.meditationtimer.timer

/**
 * Short renderings of traditional koans and Zen phrases (Mumonkan, Blue Cliff
 * Record, Zenrin-kushu, Dogen, Hakuin, and the hua-tou tradition), kept under
 * ~50 characters so they fit carved into the dial. Own concise wording
 * throughout; edit freely.
 */
val Koans = listOf(
    "Who hears?",
    "What is this?",
    "Mu.",
    "Not knowing is most intimate.",
    "The cypress tree in the garden.",
    "Your face before your parents were born?",
    "Who is dragging this corpse around?",
    "Does a dog have Buddha-nature?",
    "All things return to one. Where does the one go?",
    "What is the sound of one hand?",
    "Three pounds of flax.",
    "Wash your bowl.",
    "Have a cup of tea.",
    "The bridge flows, the water does not.",
    "Not the wind, not the flag. Mind is moving.",
    "When you meet the Buddha, who meets him?",
    "Ordinary mind is the way.",
    "Every day is a good day.",
    "The one who is not busy.",
    "Who is it that breathes?",
    "Where does the breath go when it leaves?",
    "Snow in a silver bowl.",
    "A heron hidden in the moonlight.",
    "The moon does not get wet in the water.",
    "No mud, no lotus.",
    "Sitting quietly, doing nothing.",
    "Spring comes, the grass grows by itself.",
    "The obstacle is the path.",
    "When hungry, eat. When tired, sleep.",
    "Before a thought arises, what is there?",
    "Who binds you?",
    "Bring me your mind and I will pacify it.",
    "Not one thing exists. Where can dust land?",
    "The great way has no gate.",
    "A thousand rivers, one moon.",
    "Step forward from the top of the pole.",
    "The gong fades. Where does the sound go?",
    "Before the gong is struck, where is the sound?",
    "Who is the master of this body?",
    "Look under your own feet.",
    "The blue mountain is always walking.",
    "Firewood is firewood. Ash is ash.",
    "To study the self is to forget the self.",
    "Practice and enlightenment are one.",
    "The moon in a dewdrop.",
    "Mountains are mountains again.",
    "What is the color of wind?",
    "Scoop water, the moon is in your hand.",
    "One inch of sitting, one inch of Buddha.",
    "Great doubt, great awakening.",
    "The gate stands open. Why not walk through?",
    "Nothing is hidden.",
    "This very moment, what is lacking?",
    "This very body is the Buddha.",
    "Empty-handed, holding a hoe.",
    "Walking, I ride the ox.",
    "The wooden man sings, the stone woman dances.",
    "The iron tree blooms.",
    "Swallow the river in one gulp.",
    "Birds leave no path in the sky.",
    "No snowflake falls in the wrong place.",
    "Medicine and sickness heal each other.",
    "The whole world is medicine.",
    "Why not open your own treasure house?",
    "The coin lost in the river is found in the river.",
    "Where is your original home?",
    "Ride the ox home.",
    "Return to the marketplace with open hands.",
    "Knock on the sky and listen.",
    "An old pond. A frog jumps in.",
    "Attention. Attention. Attention.",
    "Host and guest: which are you?",
    "The whole body is hands and eyes.",
    "Each branch of coral holds up the moon.",
    "A flower held up. A smile.",
    "One moon shows in every pool.",
    "When the fruit is ripe, it falls by itself.",
    "Great faith, great doubt, great effort.",
    "Listen: the sound of rain.",
    "The world is wide. Why answer the bell?",
    "If not within, where will you look?",
    "Speak and you miss it.",
    "Silence, loud as thunder.",
    "Chop wood, carry water.",
    "The whole universe is one bright pearl.",
    "Turn the light inward.",
    "What sees when the eyes close?",
    "The valley stream preaches all night."
)
